language: c

addons:
  apt:
    packages:
    - jq

env:
  global:
    - PATH=$HOME/bin:$PATH

before_install:
  - mkdir -p $HOME/bin

install:
  - true

script:
  - wget -q -O tinytex.tar.gz https://yihui.org/tinytex/TinyTeX.tar.gz
  - tar xzf tinytex.tar.gz -C $HOME
  - alias tlmgr=$HOME/.TinyTeX/bin/*/tlmgr

  - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/debian-control-texlive-in.txt
  - equivs-build debian-*
  - mv texlive-local*.deb texlive-local.deb

  - mkdir dist
  - mv tinytex.tar.gz texlive-local.deb dist/
  - ./index.sh > dist/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist
  fqdn: travis-bin.yihui.org
  on:
    branch: master
