language: c

addons:
  apt:
    packages:
    - jq
    - equivs-build

env:
  global:
    - PATH=$HOME/bin:$PATH

before_install:
  - mkdir -p $HOME/bin
  - mkdir dist

install:
  - true

script:
  - wget -q -O tinytex.tar.gz https://yihui.org/tinytex/TinyTeX.tar.gz
  - tar xzf tinytex.tar.gz -C $HOME
  - alias tlmgr=$HOME/.TinyTeX/bin/*/tlmgr

  - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/debian-control-texlive-in.txt
  - equivs-build debian-*
  - mv texlive-local*.deb texlive-local.deb

  - latest_url=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/jgm/pandoc/actions/artifacts | jq -r '.artifacts| map(select(.name == "nightly-linux")) | .[0].archive_download_url'
  - curl -L -o pandoc-linux.zip -u :$GH_TOKEN $latest_url
  - unzip -j -d $HOME/bin pandoc-linux.zip
  - mv pandoc-linux.zip tinytex.tar.gz texlive-local.deb dist/
  - ./index.sh > dist/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist
  fqdn: travis-bin.yihui.org
  on:
    branch: master
