language: haskell
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - equivs
    - python

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - mkdir -p $HOME/.local/bin

install:
  - true

script:
  - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version
  - git clone --depth=50 https://github.com/jgm/pandoc
  - cd pandoc
  - 'echo "allow-newer: true" >> stack.yaml'
  - stack setup
  - stack install --ghc-options="-O2" pandoc pandoc-citeproc
  - ls -lh ~/.local/bin
  - pandoc --version
  - pandoc-citeproc --version

  - cd ..
  - sed -i 's@\$HOME@'"$HOME"'@' TexLive.profile
  - cat TexLive.profile
  - wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/debian-control-texlive-in.txt

  - tar zxf install-tl*
  - ./install-tl*/install-tl -profile TexLive.profile
  - export PATH=$PATH:$HOME/texlive/bin/x86_64-linux
  - ./install-more-tl-pkgs.sh
  - mktexlsr
  - tar zcf texlive.tar.gz -C ~ texlive

  - equivs-build debian-*
  - mv texlive-local*.deb texlive-local.deb

  - mkdir dist
  - tar zcf pandoc.tar.gz ~/.local/bin/pandoc*
  - mv pandoc.tar.gz texlive.tar.gz texlive-local.deb dist/
  - ./index.sh > dist/index.html

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist
  fqdn: travis-bin.yihui.name
  on:
    branch: master
