on: [workflow_dispatch, pull_request]

name: build-bin

jobs:
  build-pandoc:
    name: Get daily pandoc binary
    runs-on: ubuntu-20.04
    steps:
    - name: Get pandoc artifacts list
      id: artifacts
      uses: actions/github-script@v3
      with: 
        script: |
         return await github.actions.listArtifactsForRepo({
            owner: "jgm",
            repo: "pandoc",
          })
    - name: Identify last nightly build for linux
      id: latest-artifact
      run: | 
        echo "::set-output name=artifactId::$(echo '${{steps.artifacts.outputs.result}}' | jq -r '.data.artifacts | map(select(.name == "nightly-linux")) | .[0].id')"
    - name: Get artifact download url
      id: artifact
      uses: actions/github-script@v3
      with:
        script: |
          return await github.actions.downloadArtifact({
            owner: "jgm",
            repo: "pandoc",
            artifact_id: ${{ steps.latest-artifact.outputs.artifactId }},
            archive_format: "zip",
          });
    - name: Download artifact
      run: |
        curl -L -o pandoc-linux.zip $(echo '${{steps.artifact.outputs.result}}' | jq -r '.url')
    - name: Upload as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pandoc-linux-daily
        path: pandoc-linux.zip
    - run: echo $PATH
    - name: Pandoc version
      run: |
        unzip -j -d ~/bin pandoc-linux.zip
        chmod +x ~/bin/pandoc
        ~/bin/pandoc --version > ~/pandoc.txt
        cat ~/pandoc.txt

  deploy-pandoc:
    needs: [build-pandoc]
    name: deploy built binary
    runs-on: ubuntu-20.04
    steps:
    - run: echo 'not deploying at the moment'