on: [workflow_dispatch, pull_request]

name: build-bin

jobs:
  build-pandoc:
    name: Get daily pandoc binary
    runs-on: ubuntu-20.04
    steps:
    - name: Get Artifacts
      id: artifacts
      uses: actions/github-script@v3
      with: 
        script: |
         return await github.actions.listArtifactsForRepo({
            owner: "jgm",
            repo: "pandoc",
          })
    - name: download latest
      id: latest-artifact
      run: | 
        latest-id = $(echo '${{steps.artifacts.outputs.result}}' | jq -r '.data.artifacts | map(select(.name == "nightly-linux")) | .[0].id')
        echo "::set-output name=artifactId::$latest-id"
    - run: echo ${{ steps.latest-artifact.outputs.artifactId }}

  deploy-pandoc:
    needs: [build-pandoc]
    name: deploy built binary
    runs-on: ubuntu-20.04
    steps:
    - run: echo 'not deploying at the moment'