on: [workflow_dispatch, pull_request]

name: build-bin

jobs:
  build-pandoc:
    name: Get daily pandoc binary
    runs-on: ubuntu-20.04
    steps:
    - name: install deps
      run: sudo apt-get install -y jq
    - name: Get Artifacts
      id: artifacts
      uses: actions/github-script@v3
      with: 
        result-encoding: string
        script: |
         return await github.actions.listArtifactsForRepo({
            owner: "jgm",
            repo: "pandoc",
          })
    - name: download latest
      run: | 
        echo $('${{steps.artifacts.outputs.result}}' | jq -r '.artifacts| map(select(.name == "nightly-linux")) | .[0].archive_download_url')

  deploy-pandoc:
    needs: [build-pandoc]
    name: deploy built binary
    runs-on: ubuntu-20.04
    steps:
    - run: echo 'not deploying at the moment'